# Site settings
title: '<span>M</span>atteo <span>M</span>attei'
tagline: 'Matteo Mattei'
description: "Hello, my name is Matteo Mattei and this is my personal website. I am computer engineer with a long experience in Linux system administration and web software development."
url: "http://matteomattei.com"
gravatar_img: "http://www.gravatar.com/avatar/802c6bc968e99842beff00949058d922.png"
version: 1.0
author:
  name: "Matteo Mattei"
  email: "info@matteomattei.com"
keywords:
  - matteomattei
  - matteo mattei
  - system administration
  - linux
  - matteomattei.com
  - php
  - python
  - html
  - jquery
  - computer engineer
  - nodejs
# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
paginate: 6
plugins: [jekyll-paginate, jekyll-gist]
exclude: [node_modules]
gist:
  noscript: false
